version: '3'
services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082
        networks:
            - rede-kotlin


    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091
        networks:
            - rede-kotlin

    db:
        container_name: mariadb
        image: mariadb
        networks:
            - rede-kotlin
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'

    key-manager:
        container_name: key-manager
        build: ./Key-Manager/
        restart: on-failure
        ports:
            - '50051:50051'
        networks:
            - rede-kotlin
        depends_on:
            - erp-itau
            - bcb
            - db

        environment:
            DATASOURCE_DEFAULT_URL: jdbc:mariadb://db:3306/mysql-mariadb?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
            CLIENTE_ITAU: http://erp-itau:9091/api/v1
            CLIENTE_BCB: http://bcb:8082/api/v1

    key-manager-rest:
        container_name: key-manager-rest
        build: ./Key-manager-rest/
        restart: on-failure
        ports:
            - '8080:8080'
        networks:
            - rede-kotlin
        depends_on:
            - erp-itau
            - bcb
            - db
            - key-manager

        environment:
            #GRPC_CHANNELS_KEYMANAGER_ADDRESS: key-manager:50051 aparentemente isso aqui substituia toda configuracao do channel
            KEYMANAGER_SERVER: key-manager:50051



networks:
    rede-kotlin:
        driver: "bridge"