micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${KEYMANAGER_SERVER:`localhost:50051`}'
      plaintext: true
      transport-security: true
      max-retry-attempts: 10
